package com.qverkk.kotlin.api.methods.abilities

enum class AbilitiesData constructor(val abilityName: String, val percentage: Int) {
    ANTICIPATION("Anticipation", 0),
    FREEDOM("Freedom", 0),
    SLAUGHTER("Slaughter", 50),
    OVERPOWER("Overpower", 100),
    FORCEFUL_BACKHAND("Forceful Backhand", 50),
    FLURRY("Flurry", 50),
    HURRICANE("Hurricane", 50),
    MASSACRE("Massacre", 100),
    METEOR_STRIKE("Meteor Strike", 100),
    STOMP("Stomp", 50),
    QUAKE("Quake", 50),
    DESTROY("Destroy", 50),
    BERSERK("Berserk", 100),
    ASSAULT("Assault", 50),
    PULVERISE("Pulverise", 100),
    FRENZY("Frenzy", 100),
    SNAP_SHOT("Snap Shot", 50),
    DEADSHOT("Deadshot", 100),
    TIGHT_BINDINGS("Tight Bindings", 50),
    RAPID_FIRE("Rapid Fire", 50),
    BOMBARDMENT("Bombardment", 50),
    INCENDIARY_SHOT("Incendiary Shot", 100),
    UNLOAD("Unload", 100),
    ASPHYXIATE("Asphyxiate", 50),
    OMNIPOWER("Omnipower", 100),
    DEEP_IMPACT("Deep Impact", 50),
    DETONATE("Detonate", 50),
    WILD_MAGIC("Wild Magic", 50),
    METAMORPHOSIS("Metamorphosis", 100),
    TSUNAMI("Tsunami", 100),
    REVENGE("Revenge", 50),
    DEVOTION("Devotion", 50),
    IMMORTALITY("Immortality", 100),
    REFLECT("Reflect", 50),
    REJUVENATE("Rejuvenate", 100),
    DEBILITATE("Debilitate", 50),
    BARRICADE("Barricade", 100);
}